"""Mode catalog metadata — no UI / tkinter imports (safe for web servers)."""

MODE_META = {
    "focus": {
        "title": "Focus Pulse",
        "subtitle": "Go / No-Go · response inhibition",
        "blurb": "Tap green, ignore red. Classic inhibition training.",
        "domain": "Attention & inhibition",
    },
    "memory": {
        "title": "Memory Lattice",
        "subtitle": "Sequence recall · working memory",
        "blurb": "Replay growing sequences. Set size & speed rise with level.",
        "domain": "Working memory",
    },
    "switch": {
        "title": "Switch Path",
        "subtitle": "Rule shifting · cognitive flexibility",
        "blurb": "Rules flip more often at higher levels. Stay flexible.",
        "domain": "Cognitive flexibility",
    },
    "speed": {
        "title": "Speed Mirror",
        "subtitle": "Processing speed · pattern match",
        "blurb": "More foils, less time. Pure speed under load.",
        "domain": "Processing speed",
    },
    "nback": {
        "title": "N-Back Lite",
        "subtitle": "Continuous WM update · n-back",
        "blurb": "N grows 1→4 with level. Research staple for WM training.",
        "domain": "Working memory (n-back)",
    },
    "dual": {
        "title": "Dual Stream",
        "subtitle": "Dual n-back · letter + position",
        "blurb": "Jaeggi-style dual load. Tracks two streams at once.",
        "domain": "Dual working memory",
    },
    "rotate": {
        "title": "Mind Rotate",
        "subtitle": "Mental rotation · Shepard & Metzler",
        "blurb": "Same shape rotated, or a mirror? Visuospatial skill.",
        "domain": "Visuospatial",
    },
    "stroop": {
        "title": "Color Clash",
        "subtitle": "Stroop · interference control",
        "blurb": "Name the ink, not the word. Conflict rises with level.",
        "domain": "Executive control",
    },
    "flanker": {
        "title": "Flanker Force",
        "subtitle": "Eriksen flanker · selective attention",
        "blurb": "Center arrow only. Flanks fight you more as you level.",
        "domain": "Attention & conflict",
    },
    "odd": {
        "title": "Odd Spot",
        "subtitle": "Visual search · odd-one-out",
        "blurb": "Bigger grids, subtler oddballs at high levels.",
        "domain": "Visual search",
    },
    "trail": {
        "title": "Number Path",
        "subtitle": "Trail making · sequencing",
        "blurb": "TMT-inspired paths. Alternate 1-A-2-B at higher levels.",
        "domain": "Sequencing & attention",
    },
    "span": {
        "title": "Block Span",
        "subtitle": "Corsi blocks · spatial WM",
        "blurb": "Classic spatial span. Sequences lengthen with mastery.",
        "domain": "Spatial working memory",
    },
    "calc": {
        "title": "Quick Calc",
        "subtitle": "Mental arithmetic · fluency",
        "blurb": "Harder ops and less time as levels climb.",
        "domain": "Numeracy & speed",
    },
    "category": {
        "title": "Category Flex",
        "subtitle": "Semantic set shifting",
        "blurb": "Does it fit the rule? Rules switch faster at high level.",
        "domain": "Semantic flexibility",
    },
    "simon": {
        "title": "Simon Side",
        "subtitle": "Simon task · S-R compatibility",
        "blurb": "Respond by color, ignore location. Spatial conflict training.",
        "domain": "Conflict monitoring",
    },
    "change": {
        "title": "Change Detect",
        "subtitle": "Visual WM capacity · Luck & Vogel",
        "blurb": "Encode a color array. Did anything change? Set size scales.",
        "domain": "Visual working memory",
    },
    "stop": {
        "title": "Stop Signal",
        "subtitle": "Stop-signal · Logan inhibition",
        "blurb": "Go on arrows — but freeze on STOP. SSD tightens with level.",
        "domain": "Response inhibition",
    },
    "digits": {
        "title": "Digit Reverse",
        "subtitle": "Backward digit span · verbal WM",
        "blurb": "Hear digits forward, report backward. WAIS-inspired.",
        "domain": "Verbal working memory",
    },
    "pasat": {
        "title": "Add Stream",
        "subtitle": "PASAT-lite · paced addition",
        "blurb": "Add each number to the previous under pace pressure.",
        "domain": "Attention & processing speed",
    },
    "track": {
        "title": "Object Track",
        "subtitle": "Multiple-object tracking · MOT",
        "blurb": "Track glowing targets through motion. Pylyshyn-inspired.",
        "domain": "Sustained visuospatial attention",
    },
    "opspan": {
        "title": "Op Span",
        "subtitle": "Operation span · complex WM",
        "blurb": "Solve math while storing letters. Engle complex-span style.",
        "domain": "Complex working memory",
    },
    "sart": {
        "title": "Sustained Go",
        "subtitle": "SART · sustained attention (Robertson)",
        "blurb": "Tap every digit except 3. Commission errors rise with speed.",
        "domain": "Sustained attention",
    },
    "posner": {
        "title": "Cue Focus",
        "subtitle": "Posner cueing · attention orienting",
        "blurb": "Cues predict (or mislead) target location. NIH attention classic.",
        "domain": "Attention orienting",
    },
    "symdigit": {
        "title": "Symbol Code",
        "subtitle": "SDMT-inspired · processing speed",
        "blurb": "Map symbols to digits fast. Used in MS/TBI neurology batteries.",
        "domain": "Processing speed",
    },
    "dualtask": {
        "title": "Dual Load",
        "subtitle": "Cognitive dual-task · divided attention",
        "blurb": "Letter 1-back + digit store. Dual-task training literature.",
        "domain": "Dual-task control",
    },
    "rulesearch": {
        "title": "Rule Hunt",
        "subtitle": "WCST-lite · executive set shifting",
        "blurb": "Discover the hidden sort rule. Rule changes without warning.",
        "domain": "Executive flexibility",
    },
    "rsvp": {
        "title": "Flash Stream",
        "subtitle": "RSVP · rapid visual presentation",
        "blurb": "Catch the digit in a letter stream. Attention selection under load.",
        "domain": "Selective attention",
    },
    "antisaccade": {
        "title": "Anti Saccade",
        "subtitle": "Inhibitory control · antisaccade",
        "blurb": "Flash on one side — respond on the opposite. Frontal inhibition classic.",
        "domain": "Response inhibition",
    },
    "running": {
        "title": "Running Span",
        "subtitle": "Running WM · Broadway & Engle",
        "blurb": "Stream of letters; report only the last N. Continuous updating.",
        "domain": "Working memory updating",
    },
    "tower": {
        "title": "Tower Plan",
        "subtitle": "Tower of London · planning",
        "blurb": "Choose the best next move toward the goal. Executive planning.",
        "domain": "Executive planning",
    },
    "conjunction": {
        "title": "Feature Hunt",
        "subtitle": "Conjunction search · Treisman",
        "blurb": "Find the item matching BOTH color and shape among foils.",
        "domain": "Visual attention",
    },
    "matrix": {
        "title": "Pattern Matrix",
        "subtitle": "Abstract reasoning · Raven-like",
        "blurb": "Complete the 3×3 pattern. Fluid reasoning under time pressure.",
        "domain": "Fluid intelligence",
    },
    "backspan": {
        "title": "Reverse Blocks",
        "subtitle": "Backward Corsi · spatial WM",
        "blurb": "Watch the path, tap it backward. Spatial working memory.",
        "domain": "Spatial working memory",
    },
    "cpt": {
        "title": "AX Vigil",
        "subtitle": "CPT-AX · sustained attention",
        "blurb": "Tap only when A is followed by X. Classic vigilance / ADHD battery task.",
        "domain": "Sustained attention",
    },
    "partial": {
        "title": "Flash Report",
        "subtitle": "Partial report · Sperling",
        "blurb": "Brief letter grid; report the cued row. Iconic / visual STM.",
        "domain": "Visual short-term memory",
    },
    "dichotic": {
        "title": "Two Streams",
        "subtitle": "Dichotic-style selective attention",
        "blurb": "Two words at once — report only the attended side (Hugdahl lineage).",
        "domain": "Selective attention",
    },
    "prospective": {
        "title": "Remember When",
        "subtitle": "Prospective memory · Einstein & McDaniel",
        "blurb": "Do odd/even, but remember to flag multiples of 5.",
        "domain": "Prospective memory",
    },
    "loci": {
        "title": "Memory Palace",
        "subtitle": "Method of loci / paired associates",
        "blurb": "Bind items to places, then recall. Often compared with n-back training.",
        "domain": "Episodic / associative memory",
    },
    "countkeep": {
        "title": "Keep Count",
        "subtitle": "Running total · WM updating",
        "blurb": "Add/subtract updates, ignore distractors, report the total.",
        "domain": "Working memory updating",
    },
    "serial7": {
        "title": "Serial Sevens",
        "subtitle": "Mental control · MMSE lineage",
        "blurb": "Subtract 7 repeatedly. Classic bedside cognitive / clinical test.",
        "domain": "Mental control",
    },
    "cancel": {
        "title": "Cancel Marks",
        "subtitle": "Cancellation test · visual attention",
        "blurb": "Cross out every target symbol. Used in neglect & attention screening.",
        "domain": "Visual attention",
    },
    "oddball": {
        "title": "Oddball",
        "subtitle": "Rare-target detection · P300 research",
        "blurb": "Respond only to rare targets among standards. Clinical ERP classic.",
        "domain": "Selective attention",
    },
    "choicert": {
        "title": "Choice RT",
        "subtitle": "Choice reaction time · psychomotor speed",
        "blurb": "React as fast as you can to left/right (or 4-choice). Battery staple.",
        "domain": "Processing speed",
    },
    "wordlist": {
        "title": "Word List",
        "subtitle": "RAVLT/CVLT-inspired free recall",
        "blurb": "Study a list, then recall without intrusions. Verbal memory testing.",
        "domain": "Verbal memory",
    },
    "brownpeterson": {
        "title": "Trigram Hold",
        "subtitle": "Brown–Peterson · distractor delay",
        "blurb": "Hold 3 letters while doing math. Classic STM interference paradigm.",
        "domain": "Short-term memory",
    },
}
